name: Power VS Verify

on:
  pull_request:
    branches: [ add-ipi ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.3'

    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint

    - name: Run go fmt
      run: |
        unformatted=$(IS_CONTAINER=FALSE ./hack/go-fmt.sh .)
        if [[ ! -z "${unformatted}" ]]; then
            echo "fix the gofmt issues"
            echo "${unformatted}"
            exit 1
        fi
        ##TODO: Enable verify-vendor.sh script before upstream code.
        #IS_CONTAINER=FALSE bash ./hack/verify-vendor.sh

    - name: Run go lint
      run: |
        lint=$(IS_CONTAINER=FALSE ./hack/go-lint.sh -min_confidence 0.3 $(go list -f '{{.ImportPath }}' ./...))
        if [[ ! -z "$(lint)" ]]; then
            echo "fix lint issues"
            echo "${lint}"
            exit 1
        fi

    - name: Verify codegen
      run: |
        IS_CONTAINER=FALSE bash ./hack/verify-codegen.sh

    - name: Run go vet
      run: |
        go mod vendor
        IS_CONTAINER=FALSE ./hack/go-vet.sh ./...
        if [[ $? -ne 0 ]]; then
            echo "fix go vet"
            exit 1
        fi

    - name: Build verification
      run: |
        ./hack/build.sh

    - name: Test
      run: |
        go test ./pkg/...
